command: ["python", "app.py"]
env:
  - name: PORT
    value: "8000"
  - name: DATABRICKS_HOST
    value: "https://fe-vm-leaps-fe.cloud.databricks.com"
  - name: DATABRICKS_SECRET_SCOPE
    value: "slack-bot-secrets"