name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt

    - name: Run basic syntax check
      run: |
        python -m py_compile chat_cli.py
        python -m py_compile chat_cli_openai.py
        python -m py_compile app.py
        python -m py_compile app_openai.py
        python -m py_compile example_usage.py

    - name: Run unit tests (allow failure)
      continue-on-error: true
      run: |
        pytest tests/ -v --tb=short || true

    - name: Check imports
      run: |
        python -c "import chat_cli_openai"
        python -c "import app_openai"
        echo "✅ All modules can be imported"